import { db } from '@/db';
import { posts } from '@/db/schema';

async function main() {
    const samplePosts = [
        {
            title: "Kenya's Tech Ecosystem Reaches $1 Billion Valuation",
            slug: "kenyas-tech-ecosystem-reaches-1-billion-valuation",
            excerpt: "Nairobi's Silicon Savannah continues to attract global investment",
            content: "Kenya's technology ecosystem has achieved a major milestone, reaching a cumulative valuation of over $1 billion. This achievement marks a significant turning point for East Africa's tech hub, with Nairobi's Silicon Savannah attracting unprecedented global investment. The growth has been driven by successful startups in fintech, agritech, and healthtech sectors, positioning Kenya as a leading innovation center in Africa.",
            type: "article",
            categoryId: 1,
            authorId: 3,
            featuredImage: "/images/kenya-tech.jpg",
            status: "published",
            views: 1245,
            readTime: "5 min read",
            regions: JSON.stringify(["East Africa"]),
            tags: JSON.stringify(["startups", "investment", "Kenya"]),
            publishedAt: new Date("2024-01-15T10:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Agricultural Innovation Transforms Rural Nigeria",
            slug: "agricultural-innovation-transforms-rural-nigeria",
            excerpt: "Smart farming techniques boost crop yields by 40% in Northern Nigeria",
            content: "Nigerian farmers are embracing precision agriculture and smart farming technologies, leading to remarkable improvements in crop yields across rural communities in Northern Nigeria. Through the adoption of IoT sensors, drone monitoring, and data-driven farming practices, smallholder farmers have seen their yields increase by up to 40%. This agricultural revolution is not only improving food security but also creating new economic opportunities for rural communities.",
            type: "article",
            categoryId: 3,
            authorId: 1,
            featuredImage: "/images/nigeria-farming.jpg",
            status: "published",
            views: 892,
            readTime: "6 min read",
            regions: JSON.stringify(["West Africa"]),
            tags: JSON.stringify(["agriculture", "innovation", "Nigeria"]),
            publishedAt: new Date("2024-01-14T08:30:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "South Africa Leads Renewable Energy Revolution",
            slug: "south-africa-leads-renewable-energy-revolution",
            excerpt: "Solar and wind projects set to power 2 million homes by 2025",
            content: "South Africa's renewable energy sector is experiencing unprecedented growth, with ambitious solar and wind projects on track to provide clean electricity to 2 million homes by 2025. The government's Renewable Energy Independent Power Producer Procurement Programme has attracted billions in private investment, creating thousands of jobs while addressing the country's energy crisis. This transition represents a crucial step toward sustainable development and energy independence for the nation.",
            type: "article",
            categoryId: 6,
            authorId: 4,
            featuredImage: "/images/sa-solar.jpg",
            status: "published",
            views: 2103,
            readTime: "7 min read",
            regions: JSON.stringify(["Southern Africa"]),
            tags: JSON.stringify(["renewable energy", "climate", "South Africa"]),
            publishedAt: new Date("2024-01-13T14:20:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Ghana's Healthcare System Embraces Telemedicine",
            slug: "ghanas-healthcare-system-embraces-telemedicine",
            excerpt: "Digital health platforms connect rural patients with specialists",
            content: "Ghana's Ministry of Health has launched a nationwide telemedicine initiative that is revolutionizing healthcare access for rural populations. Through mobile apps and digital platforms, patients in remote areas can now consult with specialists in urban hospitals, receive diagnoses, and access treatment plans without traveling long distances. This innovation is particularly impactful for maternal health, chronic disease management, and emergency consultations, significantly improving health outcomes across the country.",
            type: "article",
            categoryId: 4,
            authorId: 3,
            featuredImage: "/images/ghana-health.jpg",
            status: "published",
            views: 756,
            readTime: "5 min read",
            regions: JSON.stringify(["West Africa"]),
            tags: JSON.stringify(["healthcare", "telemedicine", "Ghana"]),
            publishedAt: new Date("2024-01-12T11:15:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "AfroBeats Takes Over Global Music Charts",
            slug: "afrobeats-takes-over-global-music-charts",
            excerpt: "Nigerian and Ghanaian artists dominate international playlists",
            content: "The global music industry is witnessing an unprecedented rise of African sounds, with AfroBeats artists from Nigeria and Ghana consistently topping international charts. From Billboard to Spotify's global top 50, African artists are achieving mainstream success, collaborating with international superstars, and bringing African culture to worldwide audiences. This cultural export is not only generating billions in revenue but also reshaping global perceptions of African creativity and talent.",
            type: "article",
            categoryId: 7,
            authorId: 6,
            featuredImage: "/images/afrobeats.jpg",
            status: "published",
            views: 3421,
            readTime: "4 min read",
            regions: JSON.stringify(["West Africa"]),
            tags: JSON.stringify(["music", "culture", "entertainment"]),
            publishedAt: new Date("2024-01-11T16:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Tanzania's Education Reform Shows Promising Results",
            slug: "tanzanias-education-reform-shows-promising-results",
            excerpt: "New curriculum increases STEM enrollment by 35%",
            content: "Tanzania's bold education reforms are paying off with significant improvements in STEM education enrollment and outcomes. The new curriculum, which emphasizes practical skills, technology integration, and critical thinking, has led to a 35% increase in students pursuing science, technology, engineering, and mathematics fields. Government investment in laboratory equipment, teacher training, and digital learning resources is transforming the educational landscape and preparing students for the jobs of the future.",
            type: "article",
            categoryId: 5,
            authorId: 5,
            featuredImage: "/images/tanzania-edu.jpg",
            status: "published",
            views: 634,
            readTime: "6 min read",
            regions: JSON.stringify(["East Africa"]),
            tags: JSON.stringify(["education", "STEM", "Tanzania"]),
            publishedAt: new Date("2024-01-10T09:45:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Fintech Boom Transforms Banking Across Africa",
            slug: "fintech-boom-transforms-banking-across-africa",
            excerpt: "Mobile money platforms reach 500 million users continent-wide",
            content: "Africa's fintech revolution is reshaping how millions access financial services, with mobile money platforms now serving over 500 million users across the continent. From M-Pesa in Kenya to MTN Mobile Money in West Africa, these platforms have democratized banking, enabling previously unbanked populations to save, transfer money, access credit, and make payments digitally. The fintech boom is driving financial inclusion, spurring economic growth, and creating new opportunities for entrepreneurs and small businesses throughout Africa.",
            type: "article",
            categoryId: 2,
            authorId: 2,
            featuredImage: "/images/fintech.jpg",
            status: "published",
            views: 1876,
            readTime: "8 min read",
            regions: JSON.stringify(["East Africa", "West Africa", "Southern Africa"]),
            tags: JSON.stringify(["fintech", "banking", "mobile money"]),
            publishedAt: new Date("2024-01-09T13:30:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "The Rise of African Tech Unicorns",
            slug: "the-rise-of-african-tech-unicorns",
            excerpt: "Five African startups achieve billion-dollar valuations in 2024",
            content: "African entrepreneurship is entering a golden age with multiple startups achieving unicorn status (valuations exceeding $1 billion) in 2024. Companies spanning fintech, e-commerce, logistics, and healthtech sectors are attracting major venture capital investment from global funds. This milestone represents not just financial success, but validation of Africa's innovative capacity and market potential. These unicorns are creating thousands of jobs, solving local challenges with technology, and inspiring the next generation of African entrepreneurs.",
            type: "article",
            categoryId: 1,
            authorId: 1,
            featuredImage: "/images/unicorns.jpg",
            status: "published",
            views: 2947,
            readTime: "7 min read",
            regions: JSON.stringify(["East Africa", "West Africa", "Southern Africa"]),
            tags: JSON.stringify(["startups", "unicorns", "venture capital"]),
            publishedAt: new Date("2024-01-08T10:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Senior Software Engineer - Nairobi",
            slug: "senior-software-engineer-nairobi",
            excerpt: "Join a fast-growing fintech startup in Kenya's tech hub",
            content: "We are seeking an experienced software engineer to join our engineering team at one of Kenya's fastest-growing fintech startups. You'll work on building scalable systems that serve millions of users across East Africa, collaborate with a talented team of engineers, and have the opportunity to make a significant impact on financial inclusion. Requirements include 5+ years of experience with modern web technologies, proficiency in TypeScript/Node.js, and experience with cloud platforms. Competitive salary, equity options, and flexible work arrangements offered.",
            type: "job",
            categoryId: 8,
            authorId: 3,
            featuredImage: "/images/job-engineer.jpg",
            status: "published",
            views: 456,
            readTime: "3 min read",
            regions: JSON.stringify(["East Africa"]),
            tags: JSON.stringify(["jobs", "software", "Kenya"]),
            publishedAt: new Date("2024-01-16T08:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Agricultural Specialist - Accra",
            slug: "agricultural-specialist-accra",
            excerpt: "Lead sustainable farming projects in rural Ghana",
            content: "International NGO seeks agricultural specialist for community development programs across rural Ghana. You'll lead projects focused on sustainable farming practices, work directly with smallholder farmers to implement modern agricultural techniques, and manage teams in multiple regions. The ideal candidate has a degree in agriculture or related field, 3+ years of field experience in developing countries, and strong community engagement skills. Fluency in English required; knowledge of local languages is a plus. Competitive NGO salary with comprehensive benefits package.",
            type: "job",
            categoryId: 8,
            authorId: 5,
            featuredImage: "/images/job-agri.jpg",
            status: "published",
            views: 234,
            readTime: "3 min read",
            regions: JSON.stringify(["West Africa"]),
            tags: JSON.stringify(["jobs", "agriculture", "Ghana"]),
            publishedAt: new Date("2024-01-15T12:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Healthcare Data Analyst - Cape Town",
            slug: "healthcare-data-analyst-cape-town",
            excerpt: "Analyze health data to improve patient outcomes",
            content: "Leading healthcare provider seeks data analyst to support digital health initiatives and improve patient outcomes across South Africa. You'll work with large healthcare datasets, develop predictive models for patient care, create dashboards for clinical staff, and collaborate with medical professionals to translate data insights into actionable improvements. Requirements include strong SQL and Python skills, experience with healthcare data, and understanding of statistical analysis. Bachelor's degree in data science, statistics, or related field required. Competitive salary with medical benefits and professional development opportunities.",
            type: "job",
            categoryId: 8,
            authorId: 4,
            featuredImage: "/images/job-health.jpg",
            status: "published",
            views: 312,
            readTime: "3 min read",
            regions: JSON.stringify(["Southern Africa"]),
            tags: JSON.stringify(["jobs", "healthcare", "data"]),
            publishedAt: new Date("2024-01-14T15:30:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Marketing Manager - Lagos",
            slug: "marketing-manager-lagos",
            excerpt: "Drive growth for emerging African e-commerce platform",
            content: "Fast-growing e-commerce startup seeks marketing manager to lead brand strategy and customer acquisition across Nigeria and West Africa. You'll develop and execute marketing campaigns, manage social media presence, analyze customer data to optimize conversion, and build partnerships with influencers and brands. The ideal candidate has 4+ years of digital marketing experience, proven track record of growing user bases, and deep understanding of African consumer markets. Strong analytical skills and creativity required. Attractive compensation package including equity and performance bonuses.",
            type: "job",
            categoryId: 8,
            authorId: 2,
            featuredImage: "/images/job-marketing.jpg",
            status: "published",
            views: 523,
            readTime: "3 min read",
            regions: JSON.stringify(["West Africa"]),
            tags: JSON.stringify(["jobs", "marketing", "Nigeria"]),
            publishedAt: new Date("2024-01-13T09:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "African Union Announces Continental Free Trade Update",
            slug: "african-union-announces-continental-free-trade-update",
            excerpt: "Trade volume increases 22% in first quarter",
            content: "The African Continental Free Trade Area reports significant progress in its implementation, with intra-African trade volumes increasing by 22% in the first quarter of 2024 compared to the same period last year. The African Union's trade report highlights successful tariff reductions, improved customs procedures, and enhanced trade facilitation measures across member states. Economic analysts project that full implementation of the AfCFTA could boost intra-African trade by 52% and increase manufacturing output across the continent.",
            type: "news",
            categoryId: 2,
            authorId: 2,
            featuredImage: "/images/afcfta.jpg",
            status: "published",
            views: 1567,
            readTime: "4 min read",
            regions: JSON.stringify(["East Africa", "West Africa", "Southern Africa"]),
            tags: JSON.stringify(["trade", "economy", "news"]),
            publishedAt: new Date("2024-01-17T07:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "WHO Commends Africa's Malaria Reduction Success",
            slug: "who-commends-africas-malaria-reduction-success",
            excerpt: "Malaria cases drop 30% across sub-Saharan Africa",
            content: "The World Health Organization has praised African nations for significant progress in combating malaria, with cases dropping by 30% across sub-Saharan Africa over the past three years. This achievement results from coordinated efforts including widespread distribution of insecticide-treated mosquito nets, improved access to rapid diagnostic tests, and effective antimalarial treatments. The WHO report highlights successful public health campaigns, increased funding for malaria prevention, and innovative approaches including the rollout of the RTS,S malaria vaccine in pilot programs.",
            type: "news",
            categoryId: 4,
            authorId: 3,
            featuredImage: "/images/malaria.jpg",
            status: "published",
            views: 987,
            readTime: "4 min read",
            regions: JSON.stringify(["East Africa", "West Africa", "Southern Africa"]),
            tags: JSON.stringify(["health", "malaria", "WHO"]),
            publishedAt: new Date("2024-01-16T11:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Climate Summit Yields $10B Green Investment Pledge",
            slug: "climate-summit-yields-10b-green-investment-pledge",
            excerpt: "Global investors commit to African renewable energy projects",
            content: "A landmark climate summit in Nairobi has secured major funding commitments totaling $10 billion for renewable energy projects across Africa. Global investors, development banks, and private equity funds pledged support for solar, wind, and hydroelectric projects in over 20 African countries. The investment package includes funding for grid infrastructure, energy storage solutions, and capacity building programs. Climate experts view this as a crucial step toward achieving Africa's renewable energy targets and ensuring sustainable economic development while addressing climate change challenges.",
            type: "news",
            categoryId: 6,
            authorId: 4,
            featuredImage: "/images/climate-summit.jpg",
            status: "published",
            views: 1432,
            readTime: "5 min read",
            regions: JSON.stringify(["East Africa", "West Africa", "Southern Africa"]),
            tags: JSON.stringify(["climate", "investment", "renewable energy"]),
            publishedAt: new Date("2024-01-15T14:00:00Z").toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(posts).values(samplePosts);

    console.log('✅ Posts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});